# Generated by Django 5.2.12 on 2026-04-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagedDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "engine",
                    models.CharField(
                        choices=[("mysql", "MySQL"), ("mariadb", "MariaDB")],
                        default="mysql",
                        max_length=16,
                    ),
                ),
                (
                    "image_tag",
                    models.CharField(
                        help_text="Docker image tag, e.g. 8.0, 8.4, 11, lts",
                        max_length=64,
                    ),
                ),
                (
                    "host_port",
                    models.PositiveIntegerField(
                        help_text="Host TCP port published on 0.0.0.0 (LAN-accessible).",
                        unique=True,
                    ),
                ),
                ("mysql_root_password", models.CharField(max_length=256)),
                ("mysql_database", models.CharField(blank=True, max_length=64)),
                ("container_id", models.CharField(blank=True, max_length=128)),
                ("container_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stopped", "Stopped"),
                            ("running", "Running"),
                            ("missing", "Missing"),
                            ("error", "Error"),
                        ],
                        default="stopped",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
