# Generated by Django 5.2.12 on 2026-04-03 17:58

import django.db.models.deletion
from django.db import migrations, models


def copy_root_passwords(apps, schema_editor):
    ManagedDatabase = apps.get_model("dbinstances", "ManagedDatabase")
    ManagedDatabaseUser = apps.get_model("dbinstances", "ManagedDatabaseUser")
    for m in ManagedDatabase.objects.all():
        ManagedDatabaseUser.objects.create(
            managed_database=m,
            kind="root",
            username="root",
            password=m.mysql_root_password,
            host="%",
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dbinstances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageddatabase",
            name="user_provision_error",
            field=models.TextField(
                blank=True,
                help_text="Last error from syncing application users into the server (SQL).",
            ),
        ),
        migrations.CreateModel(
            name="ManagedDatabaseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("root", "Root"), ("application", "Application")],
                        max_length=32,
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=256)),
                (
                    "host",
                    models.CharField(
                        default="%",
                        help_text="MySQL account host, e.g. % for any remote host.",
                        max_length=255,
                    ),
                ),
                (
                    "default_database",
                    models.CharField(
                        blank=True,
                        help_text="For application users: grant ALL on this database.*; if empty, uses the instance initial database; if still empty, grants on *.* (dev only).",
                        max_length=64,
                    ),
                ),
                (
                    "managed_database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="db_users",
                        to="dbinstances.manageddatabase",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "root")),
                        fields=("managed_database",),
                        name="dbinstances_manageddb_single_root",
                    ),
                ],
            },
        ),
        migrations.RunPython(copy_root_passwords, noop_reverse),
        migrations.RemoveField(
            model_name="manageddatabase",
            name="mysql_root_password",
        ),
    ]
