# Generated by Django 5.2.12 on 2026-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbinstances", "0003_engine_and_logical_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseengine",
            name="user_provision_error",
            field=models.TextField(
                blank=True,
                help_text="Last error from SQL sync (logical databases, application users, grants).",
            ),
        ),
    ]
