# Generated by Django 5.2.12 on 2026-04-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbinstances", "0004_user_provision_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseengine",
            name="host_port",
            field=models.PositiveIntegerField(
                help_text="Host TCP port published on 0.0.0.0 (LAN-accessible). If a container already exists, change this only together with the changelist action “Recreate container (keep data volume)” so Docker republishes MySQL on the new port.",
                unique=True,
            ),
        ),
    ]
