# Generated by Django 5.2.12 on 2026-04-07 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbinstances", "0005_host_port_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="DockerAdminJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("create_and_start", "Create container and start"),
                            ("recreate_container", "Recreate container"),
                            ("sync_databases_and_users", "Sync databases and users"),
                        ],
                        max_length=64,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("step", models.CharField(blank=True, max_length=64)),
                ("message", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "engine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docker_admin_jobs",
                        to="dbinstances.databaseengine",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["engine", "status"], name="dbinst_dockerjob_eng_stat"
                    )
                ],
            },
        ),
    ]
