# Generated by Django 5.2.12 on 2026-04-07 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbinstances", "0006_docker_admin_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockeradminjob",
            name="logical_database",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_jobs",
                to="dbinstances.logicaldatabase",
            ),
        ),
        migrations.AddField(
            model_name="dockeradminjob",
            name="sql_import_path",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="dockeradminjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("create_and_start", "Create container and start"),
                    ("recreate_container", "Recreate container"),
                    ("sync_databases_and_users", "Sync databases and users"),
                    ("import_sql_dump", "Import SQL dump"),
                ],
                max_length=64,
            ),
        ),
    ]
